04-oop-basic-intro-to-dom: Implement ColumnChart component
js-tasks-ru/js-20201030_victor25 pull request #5
Opened 2020-11-13 17:20 UTC by victoralsheuski

2020-11-13 18:18 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-11-14 23:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-15 21:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    crateTitleLink() {
Помните на занятии я говорил о том что использовать шаблонные строки для того чтобы создать внутреннюю структуру компонента гораздо более правильный и удобный подход?
Напомните пожалуйста почему?

2020-11-15 21:31 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    initEventListeners () {
не оставляйте пустые методы если они не используются.

2020-11-15 21:31 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    get duration () {
отлично что используете геттеры. Вопрос следующий: в данной компоненте какую проблему эти геттеры решают?

2020-11-15 21:32 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        setTimeout(this.remove.bind(this), this._duration);
вопрос: можно ли обойтись без `bind` в данном случае?

2020-11-15 21:33 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +const SUCCESS_NOTIFICATION_CLASSES = 'notification success';
данная переменная используется только в одном методе внутри компонента. Почему Вы решили вынести ее на уровень модуля?

2020-11-15 21:34 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2020-11-16 06:49 UTC, victoralsheuski commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    crateTitleLink() {
да, это я понимаю. шаблонные структуры позволяют упростить верстку и наглядность. в условиях реальных постоянно меняющих проектов это очень важно. делал не через шаблоны так как тогда еще не знал про такой подход. следующие задания делаю через шаблоны.

2020-11-16 06:50 UTC, victoralsheuski commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    initEventListeners () {
согласен. исправляю.

2020-11-16 06:52 UTC, victoralsheuski commented on 05-dom-document-loading/1-notification/index.js
> +    get duration () {
геттер позволяют делать универсальные компораторы для любых объектов, с любой вложенностью. универсальность это круто, т.к. решает проблему дублирования и прочие.

2020-11-16 06:53 UTC, victoralsheuski commented on 05-dom-document-loading/1-notification/index.js
> +        setTimeout(this.remove.bind(this), this._duration);
да, конечно можно обойтись. можно например передать лямда функцию типа так
`setTimeout( () => { this.remove() }, this._duration);`

2020-11-16 06:54 UTC, victoralsheuski commented on 05-dom-document-loading/1-notification/index.js
> +const SUCCESS_NOTIFICATION_CLASSES = 'notification success';
привык к тому, что магические переменные это зло. не знаю, как правильно баланс держать в этом. исправляю

2020-11-16 07:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-16 14:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-11-17 11:58 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    crateTitleLink() {
👍

2020-11-17 11:59 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    get duration () {
да, определенная инкапсуляция, но ни от чего не защищает в данном конкретном случае. Лучше не использовать "фишки" или "возможности" языка без конкретной необходимости. На реальном проекте это всегда вызовет вопросы

2020-11-17 12:00 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        setTimeout(this.remove.bind(this), this._duration);
👍good

2020-11-17 12:03 UTC, dosandk approved these changes
good 👍

2020-11-17 12:03 UTC, merged